resource_group_name         = "YOUR_RESOURCE_GROUP"
eventhub_namespace_name     = "YOUR_EVENTHUB_NAMESPACE"
eventhub_name               = "YOUR_EVENTHUB_NAME"
eventhub_listen_policy_name = "YOUR_LISTEN_POLICY"
eventhub_send_policy_name   = "YOUR_SEND_POLICY"
